@startuml
title Acceso de Usuario al Sistema
state c1 <<choice>>
state c2 <<choice>>
state c3 <<choice>>

[*] --> Usuario : Acceso
Usuario --> c1 : Elige tipo de entrada
c1 --> Registro : Registro de usuario
c1 --> InicioSesion : Inicio de sesión
c1 --> PerfilAnonimo : Acceso anónimo
Registro --> c2 : Crea perfil
InicioSesion --> c2 : Accede a perfil
c2 --> Perfil : Gestión de perfil
Perfil --> c3 : Configuración
PerfilAnonimo --> c3 : Configuración
c3 --> [*] : Fin
@enduml
