@startuml
title Gestión de Contenido por Derechos
state c1 <<choice>>
state c2 <<choice>>

[*] --> Contenido : Inicio
Contenido --> c1 : Clasifica derechos
c1 --> ConDerechos : Contenido con derechos
c1 --> SinDerechos : Contenido sin derechos
ConDerechos --> c2 : Contenido remunerado
SinDerechos --> c2 : Contenido no remunerado
c2 --> [*] : Fin
@enduml
